title: "Henry Woodrow"
theme: jekyll-theme-primer

# Prevent Jekyll from parsing the React project or node_modules
exclude:
  - my-app
  - my-app/*
  - my-app/**/*
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - .github
  - README.md
